### ISSUE TITLE
dont work anymore, black discord

### ISSUE THREAD

**Issue by Broccoli187** [Kayno0o/vibrant-glass-theme#1]

**Comment by CatsAndBlankets** [comment]
I looked at the glass_local.theme.css file that I got directly from BetterDiscord, and I just had to replace the segment at the bottom of the file:

.app-2rEoOp>.bg-h5JY_x {
    background: var(--background-url) !important;
    background-size: cover !important;
}

with

.app-2CXKsg>.bg-1QIAus {
    background: var(--background-url) !important;
    background-size: cover !important;
}

to get the background working again. It doesn't seem like the theme got updated in BetterDiscord at least.

**Comment by Broccoli187** [comment]
thx
