### ISSUE TITLE
Wrong link in readme.md

### ISSUE THREAD

**Issue by TheWarior73** [Kayno0o/vibrant-glass-theme#3]
In the [Tutorial](https://github.com/Kayno0o/vibrant-glass-theme#tutorial) section of the readme, the link leads to [the remote theme](https://github.com/Kayno0o/vibrant-glass-theme/blob/main/glass_remote.theme.css) instead of the [local theme](https://github.com/Kayno0o/vibrant-glass-theme/blob/main/glass_local.theme.css).
It's been here for a while now and I remember having trouble understanding why it wasn't working the first time i downloaded the theme !

**Comment by Kayno0o** [comment]
Thank you for bringing up this issue, I fixed it.
